# Generated by Django 5.1.3 on 2025-05-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=255, verbose_name='Adı Soyadı (Name Surname)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon Numarası (Phone Number)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bağışlanan Miktar (Donation Amount)')),
                ('donation_status', models.BooleanField(default=False, verbose_name='Bağış Durumu (Donation Status)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Açıklama (Explanation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Bağış',
                'verbose_name_plural': 'Bağışlar',
            },
        ),
    ]
