# Generated by Django 5.1.3 on 2025-05-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Bağış (Donation)', 'verbose_name_plural': 'Bağışlar (Donations)'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi (Creation Date)'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_status',
            field=models.CharField(choices=[('PENDING', 'Beklemede (Pending)'), ('COMPLETED', 'Tamamlandı (Completed)'), ('NOT_COMPLETED', 'Tamamlanmadı (Not Completed)')], default='PENDING', max_length=20, verbose_name='Bağış Durumu (Donation Status)'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Genel Açıklama / Tamamlanmama Nedeni (General Explanation / Reason if Not Completed)'),
        ),
    ]
